-- function Theme()
--   local actions = require("fzf-lua").actions
--   local kanagawa_theme = {
--     { "default-title" }, -- base profile
--     desc = "match telescope default highlights|keybinds",
--     fzf_opts = {
--       ["--layout"] = "reverse-list",
--       ["--marker"] = "+ ",
--       ["--pointer"] = "> ",
--     },
--     winopts = {
--       width = 0.8,
--       height = 0.8,
--       title_flags = false,
--       title_pos = "center",
--       preview = {
--         title_pos = "center",
--         hidden = false,
--         vertical = "up:45%",
--         horizontal = "right:40%",
--         layout = "flex",
--         flip_columns = 120,
--         delay = 10,
--         winopts = { number = false },
--         scrollbar = "float",
--         scrolloff = 0,
--       },
--     },
--     hls = {
--       normal = "TelescopeResultsNormal",
--       border = "TelescopeResultsBorder",
--       title = "TelescopeResultsTitle",
--       help_normal = "TelescopeResultsNormal",
--       help_border = "TelescopeResultsNormal",
--       preview_normal = "TelescopePreviewNormal",
--       preview_border = "TelescopePreviewBorder",
--       preview_title = "TelescopePreviewTitle",
--       path_linenr = "Special",
--       path_colnr = "Special",
--       live_prompt = "Special",
--       scrollbar = "Special",
--     },
--     fzf_colors = {
--       ["fg"] = { "fg", "TelescopeResultsNormal" },
--       ["bg"] = { "bg", "TelescopeResultsNormal" },
--       ["hl"] = { "fg", "TelescopeMatching" },
--       ["fg+"] = { "fg", "TelescopeSelection" },
--       ["bg+"] = { "bg", "TelescopeSelection" },
--       ["hl+"] = { "fg", "TelescopeMatching" },
--       ["info"] = { "fg", "TelescopePreviewTitle" },
--       ["border"] = { "fg", "TelescopeResultsBorder" },
--       ["gutter"] = "-1",
--       ["query"] = { "fg", "TelescopePromptQuery" },
--       ["prompt"] = { "fg", "TelescopePromptNormal" },
--       ["pointer"] = { "fg", "TelescopeTitle" },
--       ["marker"] = { "fg", "TelescopeSelectionCaret" },
--       ["header"] = { "fg", "TelescopeTitle" },
--       ["scrollbar"] = { "fg", "TelescopeTitle" },
--     },
--     files = {
--       cwd_prompt = false,
--       cwd_header = false,
--     },
--     grep = {
--       prompt = "> ",
--     },
--     diagnostics = {
--       file_icons = false,
--       multiline = false,
--       icon_padding = " ",
--     },
--     lsp = {
--       jump1 = true,
--     },
--     keymap = {
--       builtin = {
--         true,
--         ["<C-d>"] = "preview-page-down",
--         ["<C-u>"] = "preview-page-up",
--         ["<A-p>"] = "toggle-preview",
--       },
--       fzf = {
--         true,
--         ["ctrl-d"] = "preview-page-down",
--         ["ctrl-u"] = "preview-page-up",
--         ["ctrl-q"] = "select-all+accept",
--       },
--     },
--     actions = {
--       files = {
--         ["enter"] = actions.file_edit_or_qf,
--         ["alt-enter"] = actions.file_vsplit,
--         ["alt-q"] = actions.file_sel_to_qf,
--       },
--     },
--     buffers = {
--       keymap = { builtin = { ["<C-d>"] = false } },
--       actions = {
--         ["ctrl-x"] = false,
--         ["ctrl-d"] = { actions.buf_del, actions.resume },
--       },
--     },
--     defaults = {
--       git_icons = false,
--       file_icon_padding = " ",
--     },
--     file_ignore_patterns = {
--       "node_modules",
--       "cache",
--       -- "yarn.lock",
--       -- "bun.lockb",
--     },
--   }
--   return kanagawa_theme
-- end
--
-- return {
--   -- Plugin: fzf-lua.nvim
--   -- URL: https://github.com/ibhagwan/fzf-lua
--   -- Description: A highly extendable fuzzy finder over lists.
--   "ibhagwan/fzf-lua",
--   dependencies = {
--     "echasnovski/mini.icons",
--   },
--   config = function()
--     require("fzf-lua").setup(Theme())
--     -- require("fzf-lua").setup()
--   end,
--   keys = {
--     {
--       "<leader>fg",
--       function()
--         require("fzf-lua").live_grep()
--       end,
--       desc = "Live grep",
--       noremap = true,
--     },
--     {
--       "<leader>fG",
--       function()
--         require("fzf-lua").grep()
--       end,
--       desc = "Grep for",
--       noremap = true,
--     },
--     {
--       "<leader>f;",
--       function()
--         require("fzf-lua").resume()
--       end,
--       noremap = true,
--       desc = "Resume search",
--     },
--     {
--       "<leader>ft",
--       function()
--         require("fzf-lua").diagnostics_workspace()
--       end,
--       noremap = true,
--       desc = "List diagnostics for all open buffers",
--     },
--   },
-- }
return {}
